// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ItemsTransactions.Models
{
    public partial class Item
    {
        public Item()
        {
            Balance = new HashSet<Balance>();
            ItemTransactions = new HashSet<ItemTransactions>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int UnitId { get; set; }
        public int CategoryId { get; set; }

        public virtual Category Category { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<Balance> Balance { get; set; }
        public virtual ICollection<ItemTransactions> ItemTransactions { get; set; }
    }
}