// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ItemsTransactions.Models
{
    public partial class Warhouse
    {
        public Warhouse()
        {
            Balance = new HashSet<Balance>();
            ItemTransactions = new HashSet<ItemTransactions>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string WarHouseName { get; set; }

        public virtual ICollection<Balance> Balance { get; set; }
        public virtual ICollection<ItemTransactions> ItemTransactions { get; set; }
    }
}